name: Murder
author: TheNewHEROBRINE - ArchonKlaus
version: 1.0
api: [3.0.0]
main: TheNewHEROBRINE\Murder\MurderMain
load: POSTWORLD

permissions:
 murder:
  children:
   murder.command:
    children:
     murder.command.join:
      default: true
     murder.command.quit:
      default: true
     murder.command.setarena:
      default: op
